### ISSUE TITLE
result of clustering is inconsistent regarding "sizes"

### ISSUE THREAD

**Issue by behrica** [generateme/fastmath#12]
I noticed that the map comming back from clustering is "structurally different", depending how many (non-empty !) clusters it finds.

If I ask for 5 clusters, I would expect that the map I get back always has:

:clusters = 5
:sizes (s1 s2 s3 s4 s5)

I get sometimes this:

```
  :sizes = ( 97 53 0 )
  :clusters = 2
```

**Comment by genmeblog** [comment]
Just checked in the source code. Well, not really true (It seems I was wrong above):
https://github.com/haifengl/smile/blob/master/core/src/main/java/smile/clustering/PartitionClustering.java#L62

The last index contains number of outliers. So `cluster` contains number of clusters + 1 (for outliers). So it can it can contain 0 length clusters included.

Sorry for misleading you.
