### ISSUE TITLE
Fastmath always loads MKL binaries

### ISSUE THREAD

**Issue by mikub** [generateme/fastmath#15]
Hi there!
We love fastmath! :pray:  
Just a small nitpick (it actually broke our deployment pipeline :smile: ):
Fastmath includes `com.github.haifengl/smile-mkl` dependency which may lead to substantial resources (~800MB) being downloaded and included in the build.

![image](https://user-images.githubusercontent.com/674012/161950591-934e1a0b-df4d-4fb5-94b7-aa91794fa7df.png)

This should be either configurable or at least mentioned in the Readme so as users may plan for this and optionally exclude this dependency from their deps tree.

Cheers
Miro

**Comment by tomekw** [comment]
Looks like `smile-*` deps are pulled in but never used?

**Comment by genmeblog** [comment]
Thanks. I need to check if I can get rid them of. Generally Smile is used in several places (optimization, clustering, stats) and as far as I remember some algorithms rely on mkl.

**Comment by tomekw** [comment]
Thank you @genmeblog! The thing is it increases our artifact size from 151 MB to 1 GB :)

**Comment by genmeblog** [comment]
Yes... I'm aware of this. And more people complained about the size.

When I exclude smile-mkl, some things are not working - need to investigate what and when...

**Comment by genmeblog** [comment]
Ok, when I turn off MKL, OpenBlas is loaded instead, however... my test suite (which is `lein codox`, which runs examples defined in `metadoc`) fails with `Subprocess failed (exit code: 139)`. So generally some things are not working without MKL...

**Comment by tomekw** [comment]
@genmeblog we use your awesome clojure2d library to do some basic drawing (put some text onto an image background). Could we use some "lite" version instead?

**Comment by genmeblog** [comment]
The option is to release version without MKL with a annotation about the potential issues. I need to verify if clojure2d is able to stable operate without MKL. `reduce-colors` and `gradient` related functions rely on Smile, hence may try to load BLAS/LAPACK in certain conditions.

**Comment by tomekw** [comment]
@genmeblog that's the entirety of the c2d API we use:

![image](https://user-images.githubusercontent.com/198371/162006455-2b6f6d69-c752-4027-8a1b-c7f43fc950d7.png)

**Comment by genmeblog** [comment]
I can't propose anything more than exclusion of MKL. I need to carefuly test and assure that things around fastmath will work.

**Comment by genmeblog** [comment]
@mikub I decided to update README and describe how to remove MKL and what's the impact. As far as I tested, most things should work on OpenBlas, however I have some issues during build. That means that by default MKL will be included but can be easily removed.

I'll exclude MKL from Clojure2d - it has been tested already (thanks @tomekw) and works on OpenBlas without the problems.
