### ISSUE TITLE
add ZAGA distribution

### ISSUE THREAD

**Issue by aaelony** [generateme/fastmath#18]
As per discussion on Slack, useful distributions might be added to the already available list. 

A somewhat exhaustive list for implementation might be [here](https://github.com/cran/gamlss.dist/blob/master/NAMESPACE) as described in the [gamlss.dist R package](https://www.rdocumentation.org/packages/gamlss.dist/versions/6.0-3), including the ZAGA (Zero Adjusted Gamma) distribution.

Thanks for this excellent library!

**Comment by genmeblog** [comment]
Thanks! Huge list :) Maybe you want to select some most important ones?

**Comment by genmeblog** [comment]
ZAGA is implemented now in the latest snapshot. Verified against R. 

```
(def zaga (distribution :zaga {:nu 0.2 :mu 1.0 :sigma 2.0}))

(pdf zaga 2.0) ;; dZAGA
;; => 0.056269645152636466
(cdf zaga 2.0) ;; pZAGA
;; => 0.877189123353342
(icdf zaga 0.877189) ;; qZAGA
;; => 1.999997808161464
(->seq zaga 5) ;; random sampling
;; => (5.018629710149659 2.940219706530564E-5 0.03546063560460525 7.729955570235061 0.0)
(take 5 (->seq zaga))
;; => (0.05492161982459712 0.3927129129794207 0.0 0.006807764778811914 1.2644121020499126)
(->seq zaga 5 :uniform) ;; uniform sampling
;; => (0.0 0.0 2.0009003090803393E-4 0.05294466738236345 0.1262474855337676)
(->seq zaga 5 :systematic) ;; systematic sampling
;; => (0.0 2.3302775737303754E-4 0.039172264996012 0.3671356567919316 1.998563228048098)
(->seq zaga 5 :stratified) ;; stratified sampling
;; => (0.0 0.0018150201315259252 0.0782555215113504 0.5767730810426407 3.294239644450976)
```

Please list a couple more to be implemented or propose a PR (here is how ZAGA is implemented: https://github.com/generateme/fastmath/blob/master/src/fastmath/random.clj#L1570-L1628)

**Comment by aaelony** [comment]
Wow! Thanks for tackling ZAGA so quickly.

The main ones from my perspective are:
- [ZANBI and ZINBI](https://www.rdocumentation.org/packages/gamlss.dist/versions/6.0-3/topics/ZANBI) 
- [ZIP2](https://www.rdocumentation.org/packages/gamlss.dist/versions/6.0-3/topics/ZIP2)
- [ZABB](https://www.rdocumentation.org/packages/gamlss.dist/versions/6.0-3/topics/ZABB)

Thanks again!

**Comment by genmeblog** [comment]
* new distributions (based on R package `gamlss.dist`):
    - `:zaga` - zero adjusted gamma distribution
	- `:nbi` - negative binomial type I
	- `:zinbi` - zero inflated negative binomial type I
	- `:zanbi` - zero altered negative binomial type I
	- `:zip` - poisson zero inflated
	- `:zip2` - zero inflated poisson 2
	- `:exgaus` - ex-Gaussian
	- `:zabi` - zero adjusted binomial
	- `:zibi` - binomial zero inflated
	- `:bb` - beta binomial
	- `:zabb` - zero adjusted beta binomial
	- `:zibb` - zero inflated beta binomial

Roughly tested, can you verify them on your side @aaelony ?

**Comment by aaelony** [comment]
Very nice. I'll try to look at these this week.

**Comment by genmeblog** [comment]
Cool. Some of them can be added to the [fitdistr](https://github.com/generateme/fitdistr) if you're interesting in distribution fitting.

**Comment by genmeblog** [comment]
ZAGA and some others are added, please open new issue if you need anything more.

**Comment by aaelony** [comment]
Thank-you, this is fantastic.
