### ISSUE TITLE
ClojureScript support

### ISSUE THREAD

**Issue by zane** [generateme/fastmath#19]
It would be great to have ClojureScript support for parts of fastmath, especially `fastmath.random`.

**Comment by genmeblog** [comment]
It would be, indeed :) But I'm afraid It's not possible without rewriting parts of Java libraries supporting fastmath (like Apache Commons Math, SSJ, Smile, jafama.fastmath).

**Comment by genmeblog** [comment]
In such case I will definitely need a support here. I've never written anything in CLJS or JS and don't know tooling/libraries. Anyway, happy to support this if analogues were found.

**Comment by genmeblog** [comment]
It's out of scope of this project. As stated above I can support if anyone wants to do this.
