### ISSUE TITLE
unable to use the v1.3.0-SNAPSHOT due to `[clj-boost "0.0.4"]`

### ISSUE THREAD

**Issue by adicirstei** [generateme/fastmath#2]
If I try to launch `lein repl` in master branch I get this error. I managed to pinpoint it to `[clj-boost "0.0.4"]` dependency by commenting them out one by one. I am not an expert. I got to this problem when I tried to run the current version of `Clojure2D/clojure2d-examples`.

```text
Could not find artifact jdk.tools:jdk.tools:jar:1.8 at specified path C:\Program Files\Java\jre1.8.0_191/../lib/tools.jar
This could be due to a typo in :dependencies, file system permissions, or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
```

Regards,
Adrian

**Comment by genmeblog** [comment]
Do you run this on Windows?

**Comment by adicirstei** [comment]
On windows 10 64 bits. Indeed.

**Comment by genmeblog** [comment]
I've just checked it on Windows under Cygwin and REPL run without any errors. There is only problem with xgboost classifier. I'm checking one more thing. Stay tuned.

**Comment by genmeblog** [comment]
Please checkout examples again and before `lein repl` uncomment two commented lines.

**Comment by genmeblog** [comment]
I don't guarantee that it works. If not, I'll probably prepare version without xgboost (which is nasty in terms of dependencies and windows native library)

**Comment by adicirstei** [comment]
same issue. Sorry! What is this supposed to accomplish?

**Comment by genmeblog** [comment]
Hmmm... strange, I'll give another try on vanilla installation.

**Comment by adicirstei** [comment]
I managed to have it load by using java from JDK folder instead of JRE. As of the tools.jar is in JDK not JRE.

No jar needed in project lib folder.

Hope this makes sense.

**Comment by genmeblog** [comment]
Ah yes, always use JDK for Clojure.

**Comment by genmeblog** [comment]
So I close it.
