### ISSUE TITLE
contributor guide should probably mention the `:dev` profile

### ISSUE THREAD

**Issue by daslu** [generateme/fastmath#36]
https://github.com/generateme/fastmath/wiki/Documenting-Fastmath-in-Clay
`:dev` seems to be the relevant lein profile for developing the docs.

**Comment by genmeblog** [comment]
When developing (in Emacs in my case) `:dev` profile is used by default autmatically when `cider-jack-in`

**Comment by daslu** [comment]
Oh, thanks. I forgot that about Leiningen.
