### ISSUE TITLE
Question about license

### ISSUE THREAD

**Issue by willcohen** [generateme/fastmath#4]
Since the code of this library includes primitive-math, which is MIT licensed, does fastmath’s license need to be something which at a minimum retains the attribution requirements of MIT, like MIT or Apache? It seems like the Unlicense can’t public domain something which is already MIT.

**Comment by genmeblog** [comment]
Good issue. Thanks for spotting it out. I wonder if I can mark certain functions as licenced under different licence?
If not I probably change licence to the most matching one.

**Comment by willcohen** [comment]
I’m definitely not a lawyer but I suspect that trying to mark different functions individually might end up being pretty complicated for users to understand. 

I’d say just using MIT is probably the easiest option — it solves the issue with conforming to primitive-math’s license, is more understandable to users, and is about as close in spirit to Unlicense as you can get with a commonly used license.

Separately, thanks for the library! It’s quite helpful!

**Comment by genmeblog** [comment]
Thank you and enjoy!

I changed to MIT starting from 1.5.3 version (including SNAPSHOT).
