### ISSUE TITLE
How to call frandom with 2-3 arguments wihout getting ArityException?

### ISSUE THREAD

**Issue by holyjak** [generateme/fastmath#5]
According to https://generateme.github.io/fastmath/fastmath.random.html#var-frandom, `frandom` can be called with 1-3 params. Yet when I try to provide `mx` and send it two, it fails:

```clojure
🐟  clj -Sdeps '{:deps {generateme/fastmath {:mvn/version "2.0.5"}}}'
user=> (require '[fastmath.random :as fm.rand])
user=> (fm.rand/frandom (fm.rand/distribution :gamma) 1)
Execution error (ArityException) at fastmath.protocols/eval1001$fn$G (protocols.clj:10).
Wrong number of args (2) passed to: fastmath.random/eval4162/fn--4185
```

What am I doing wrong? Thank you!

**Comment by holyjak** [comment]
My bad, I see that when I pass in a distribution I cannot use the mn, mx b/c the distribution determines those. I should have used `(fm.rand/distribution :uniform-real {:lower 0 :upper 1 })`

**Comment by genmeblog** [comment]
You call `random` on distribution, and distribution defines what ranges to return. If you want to control distribution apply distribution parameters.

There are several option to gather random samples. There are predefined functions which can return uniformly distributed and normal distributed samples. Here are couple of examples:

```clojure
(r/drand) ;; => 0.9141529509421812
(r/drand 100) ;; => 47.33696397326038
(r/drand -1 1) ;; => -0.8813242648403063
;; or
(r/drandom (r/distribution :uniform-real {:lower -100 :upper 100})) ;; => 4.2439362972221915

(r/drandom (r/rng :mersenne)) ;; => 0.4581085453647453
(r/drandom (r/rng :mersenne) 100) ;; => 29.73486030385328
(r/drandom (r/rng :mersenne) -1 1) ;; => -0.8610827170659228

;; equivalent
(r/drandom (r/distribution :normal)) ;; => -0.5090072148143238
(r/grand) ;; => 1.7983003158101392
```
