### ISSUE TITLE
Using the triangle grid - possible bug?

### ISSUE THREAD

**Issue by apirogov** [generateme/fastmath#8]
Hello, I'm not sure whether I am using the library wrong, but I seem unable to get all triangles addressed, only every second one. I tried passing a third coordinate to toggle up/down triangles to cell->mid without effect. Can you give a hint on how to work with the triangle grid correctly?

What seems weird is that e.g. 

    user=> (g/corners gr (g/cell->mid gr [0 0]))

and

    user=> (g/corners gr (g/cell->mid gr [1 0]))

give the same results for triangular grids. (Same for 2/3, 4/5 etc.) I thought maybe even/odd x coordinates are supposed to alternate up/down triangles? But this seems to be broken broken.

Thanks in advance!

**Comment by genmeblog** [comment]
Hi. Thanks. I'll check it today. Triangles were tricky and yeah, maybe there is some bug or not obvious way of using.

**Comment by genmeblog** [comment]
Ok, I can confirm, there is something strange here. Need to figure out why (and where) I'm loosing the information about up/down position.

**Comment by genmeblog** [comment]
I've just pushed fix in `2.1.4`. Thanks for spotting this out!

**Comment by apirogov** [comment]
Thanks for the quick fix, now it works fine!

But I have another question: Is there a special reason why the triangles are not equilateral? When I set the size, it seems that the side along the x axis is of the specified size, and also the height is of that size, but this means that the triangles are "stretched" into the y axis. 

I am doing geometric stuff with circles intersecting triangle corners, so for my use case it matters a lot.
See [here](https://imgur.com/a/lhKRoPx).

Was that a design decision for some purpose? If not, would you mind patching the scaling so that the triangles become equilateral?

If you are not going to change it, do you have a suggestion how would be the most elegant way to get myself a grid of equilateral triangles? I would prefer not having to carry around a scaling factor that I have to apply to all coordinates or wrap all calls to the library. Then maybe it would suffice to add a variant with scaling (in addition to translation) to the grid constructor function?

Thanks in advance!

**Comment by genmeblog** [comment]
Oh. They should be equilateral! So there is another bug. If you are able to fix it, please do. Possibly there is another bug with skewed square which should be a rhombus. I'll take a look at it too. Thanks!

**Comment by apirogov** [comment]
Unfortunately I'm quite new to Clojure. But what I can see is that in the triangle-corners function I think a factor of sqrt(3)/2 is missing for scaling the height... A equilateral triangle with sidelength x has a height of y = x*sqrt(3)/2. Hope it helps!

**Comment by genmeblog** [comment]
Yep. Indeed it's wrong. It's derived out of rhombus, which is actually quadrilateral. So both things should be fixed. The change will affect also functions converting cell -> euclidean coords and back, also middle point. I'll try to make it today, but not promise it.

**Comment by genmeblog** [comment]
@apirogov looks like I fixed that in the newest version. Could you verify this please?

**Comment by apirogov** [comment]
I tried with the same example as before, now it works fine (cannot say anything about the rhombus variant, but if it is derived from that, should be fine too, I guess). Thanks for fixing!

**Comment by genmeblog** [comment]
Thanks for verifying. Rhombus should be also ok then.
